### ISSUE TITLE
Shimmer doesn't fit the stock box correctly

### ISSUE THREAD

**Issue by worldwidewaves** [worldwidewaves/Cookie-Stonks#10]
<img width="117" alt="Screenshot_2" src="https://user-images.githubusercontent.com/17983606/171398849-00487593-fad5-4e55-bb83-758109bba1e6.png">

**Comment by Nnnes** [comment]
Looks like the translations are reflowing the buttons to a new line.

CSS can replicate the "shimmer" effect pretty accurately while eliminating the need for hardcoded sizes. An empty `div` placed where the Cookie Stonks `canvas` is with

```css
element.style {
    position: absolute;
    top: 0;
    left: -1px;
    width: calc(100% + 2px);
    height: calc(100% + 1px);
    box-shadow: inset 0 0 10px #/* color */;
    z-index: 100;
    pointer-events: none;
}
```

(`#c62813` for wrath, `#ffc35f` for gold) is similar to the original.

![image](https://user-images.githubusercontent.com/28599170/171459848-7f569e45-f170-4774-a0bb-7850b66e9013.png)

old `canvas` on the left, new `div` on the right
